<a href="https://colab.research.google.com/github/buketecrinozturk/Datamining/blob/main/apriori.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DRIVE bağlanma kodu

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/gdrive')

Mounted at /content/gdrive

Kütüphaneleri Ekliyoruz

In [ ]:
import pandas as pd

Veri setini Drive'dan çekiyoruz

In [ ]:
dataset = pd.read_csv(r'/content/gdrive/My Drive/veri_madenciligi/Market_Basket_Optimisation.csv');

Veri setini gösterme kısmı

In [ ]:
display(pd.DataFrame(dataset))

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7496,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
dataset.shape

(7500, 20)

Verileri liste haline getiriyoruz

In [ ]:
transactions = []
for i in range(0, 7500):
 transactions.append([str(dataset.values[i,j]) for j in range(0,20)])

Apriori algoritması için kuralları belirliyoruz

In [18]:
!pip install apyori 
from apyori import apriori
rules = apriori(transactions = transactions, min_support = 0.003, min_cinfidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5973 sha256=5b5f31a9c3988e27bb9bb931105633dd4cb15687404dc7812b274568cac1eb19
  Stored in directory: /root/.cache/pip/wheels/1b/02/6c/a45230be8603bd95c0a51cd2b289aefdd860c1a100eab73661
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

Kuralları listeleyip results değişkenine atıyoruz

In [19]:
results = list(rules)

In [20]:
results

[RelationRecord(items=frozenset({'cottage cheese', 'brownies'}), support=0.0034666666666666665, ordered_statistics=[OrderedStatistic(items_base=frozenset({'brownies'}), items_add=frozenset({'cottage cheese'}), confidence=0.10276679841897234, lift=3.2384495300096323), OrderedStatistic(items_base=frozenset({'cottage cheese'}), items_add=frozenset({'brownies'}), confidence=0.10924369747899158, lift=3.2384495300096323)]),
 RelationRecord(items=frozenset({'light cream', 'chicken'}), support=0.004533333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken'}), items_add=frozenset({'light cream'}), confidence=0.07555555555555557, lift=4.8433048433048445), OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.2905982905982906, lift=4.843304843304844)]),
 RelationRecord(items=frozenset({'mushroom cream sauce', 'escalope'}), support=0.005733333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'escalope'}), items_add=frozenset({'mushroom cream sauce'}), confidence=0.0722689075630252, lift=3.790327319739084), OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.30069930069930073, lift=3.7903273197390845)]),
 RelationRecord(items=frozenset({'pasta', 'escalope'}), support=0.005866666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'escalope'}), items_add=frozenset({'pasta'}), confidence=0.07394957983193277, lift=4.700185158809287), OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.37288135593220345, lift=4.700185158809287)]),
 RelationRecord(items=frozenset({'tomato juice', 'fresh bread'}), support=0.004266666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fresh bread'}), items_add=frozenset({'tomato juice'}), confidence=0.09907120743034055, lift=3.2732777785354807), OrderedStatistic(items_base=frozenset({'tomato juice'}), items_add=frozenset({'fresh bread'}), confidence=0.14096916299559473, lift=3.273277778535481)]),
 RelationRecord(items=frozenset({'honey', 'fresh tuna'}), support=0.004, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fresh tuna'}), items_add=frozenset({'honey'}), confidence=0.17964071856287425, lift=3.795226448511428), OrderedStatistic(items_base=frozenset({'honey'}), items_add=frozenset({'fresh tuna'}), confidence=0.08450704225352113, lift=3.7952264485114275)]),
 RelationRecord(items=frozenset({'fromage blanc', 'honey'}), support=0.0033333333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'honey'}), confidence=0.2450980392156863, lift=5.178127589063795), OrderedStatistic(items_base=frozenset({'honey'}), items_add=frozenset({'fromage blanc'}), confidence=0.07042253521126761, lift=5.178127589063795)]),
 RelationRecord(items=frozenset({'ground beef', 'herb & pepper'}), support=0.016, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef'}), items_add=frozenset({'herb & pepper'}), confidence=0.1628222523744912, lift=3.2915549671393096), OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2915549671393096)]),
 RelationRecord(items=frozenset({'ground beef', 'tomato sauce'}), support=0.005333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef'}), items_add=frozenset({'tomato sauce'}), confidence=0.05427408412483039, lift=3.8401474616625277), OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.37735849056603776, lift=3.840147461662528)]),
 RelationRecord(items=frozenset({'light cream', 'olive oil'}), support=0.0032, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.20512820512820515, lift=3.120611639881417), OrderedStatistic(items_base=frozenset({'olive oil'}), items_add=frozenset({'light cream'}), confidence=0.0486815415821501, lift=3.120611639881417)]),
 RelationRecord(items=frozenset({'whole wheat pasta', 'olive oil'}), support=0.008, ordered_statistics=[OrderedStatistic(items_base=frozenset({'olive oil'}), items_add=frozenset({'whole wheat pasta'}), confidence=0.12170385395537525, lift=4.130221288078346), OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.130221288078346)]),
 RelationRecord(items=frozenset({'shrimp', 'pasta'}), support=0.005066666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050848, lift=4.514493901473151), OrderedStatistic(items_base=frozenset({'shrimp'}), items_add=frozenset({'pasta'}), confidence=0.07102803738317756, lift=4.51449390147315)])]

Sonuçların görselleştirilmesi

In [21]:
def inspect(results):
    lhs         =[tuple(result[2][0][0])[0] for result in results]
    rhs         =[tuple(result[2][0][1])[0] for result in results]
    supports    =[result[1] for result in results]
    confidences =[result[2][0][2] for result in results]
    lifts        =[result[2][0][3] for result in results]
    return list (zip(lhs, rhs, supports, confidences, lifts))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ["Left hand side", "Right hand side", "Support", "Confidence", "Lift"])

Son olarak, görselleştirmelerini kolaylaştırmak için bu değişkenleri tek bir veri çerçevesinde saklarız.

In [22]:
resultsinDataFrame

   Left hand side       Right hand side   Support  Confidence      Lift
0        brownies        cottage cheese  0.003467    0.102767  3.238450
1         chicken           light cream  0.004533    0.075556  4.843305
2        escalope  mushroom cream sauce  0.005733    0.072269  3.790327
3        escalope                 pasta  0.005867    0.073950  4.700185
4     fresh bread          tomato juice  0.004267    0.099071  3.273278
5      fresh tuna                 honey  0.004000    0.179641  3.795226
6   fromage blanc                 honey  0.003333    0.245098  5.178128
7     ground beef         herb & pepper  0.016000    0.162822  3.291555
8     ground beef          tomato sauce  0.005333    0.054274  3.840147
9     light cream             olive oil  0.003200    0.205128  3.120612
10      olive oil     whole wheat pasta  0.008000    0.121704  4.130221
11          pasta                shrimp  0.005067    0.322034  4.514494

**Şimdi, bu nihai çıktıları azalan lift sırasına göre sıralıyoruz.**

In [25]:
resultsinDataFrame.nlargest(n = 12, columns = "Lift")

   Left hand side       Right hand side   Support  Confidence      Lift
6   fromage blanc                 honey  0.003333    0.245098  5.178128
1         chicken           light cream  0.004533    0.075556  4.843305
3        escalope                 pasta  0.005867    0.073950  4.700185
11          pasta                shrimp  0.005067    0.322034  4.514494
10      olive oil     whole wheat pasta  0.008000    0.121704  4.130221
8     ground beef          tomato sauce  0.005333    0.054274  3.840147
5      fresh tuna                 honey  0.004000    0.179641  3.795226
2        escalope  mushroom cream sauce  0.005733    0.072269  3.790327
7     ground beef         herb & pepper  0.016000    0.162822  3.291555
4     fresh bread          tomato juice  0.004267    0.099071  3.273278
0        brownies        cottage cheese  0.003467    0.102767  3.238450
9     light cream             olive oil  0.003200    0.205128  3.120612